routes/web.php
<?php

use App\Http\Controllers\AnswersController;
use App\Http\Controllers\AssignmentsController;
use App\Http\Controllers\FavoritesController;
use App\Http\Controllers\QuestionsController;
use App\Http\Controllers\QuizController;
use App\Http\Controllers\QuizequestionController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\VotesController;
use App\Models\User;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('home');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');


Route::get('userPhoto', [UsersController::class, 'userPhoto'])->middleware(['auth'])->name('userPhoto');
Route::post('userPhoto', [UsersController::class, 'userPhotoUplaod'])->middleware(['auth'])->name('userPhoto.upload');
Route::get('notifications', [UsersController::class, 'notifications'])->middleware(['auth'])->name('notifications');
Route::post('notifyStudents/{assignment}', [AssignmentsController::class, 'notifyStudents'])->middleware(['auth', 'checkTeacher'])->name('notifystudents');

Route::resource('questions', QuestionsController::class)->except('show');

Route::get('questions/{slug}',[QuestionsController::class, 'show'])->name('questions.show');
Route::post('questions/searchById',[QuestionsController::class, 'showById'])->name('questions.showById');

Route::post('questions/{question}/favorite',[FavoritesController::class, 'store'])->name('questions.favorite');
Route::delete('questions/{question}/unfavorite',[FavoritesController::class, 'destroy'])->name('questions.unfavorite');

Route::post('question/{question}/vote/{vote}', [VotesController::class, 'voteQuestion'])->name('questions.votes');
Route::post('answers/{answer}/vote/{vote}', [VotesController::class, 'voteAnswer'])->name('answers.votes');

Route::resource('questions.answers', AnswersController::class)->except(['index','show','create']);
Route::put('answers/{answer}/best-answer',[AnswersController::class, 'bestAnswer'])->name('answers.bestAnswer');

Route::get('/assignmentsindex',function(){
    return view('assignements.assignementshome');
})->middleware(['auth', 'checkTeacher'])->name('assignment.home');

Route::get('/assignmentsindexstudent',function(){
    $teachers = User::where('type','Teacher')->get();
    return view('assignements.assignementshomestudent',compact(['teachers']));
})->middleware(['auth', 'checkStudent'])->name('assignment.homestudent');

Route::resource('assignments', AssignmentsController::class)->middleware(['auth', 'checkTeacher']);

// Route::post('quiz/teacher', [QuizController::class, ''])->middleware(['auth']);
Route::post('students/assignments',[AssignmentsController::class, 'acceptAssignment'])->middleware(['auth', 'checkStudent'])->name('students.assignment.accept');
Route::get('students/assignments',[AssignmentsController::class, 'indexStudent'])->middleware(['auth', 'checkStudent'])->name('students.assignment.index');
Route::get('students/assignments/{assignment}',[AssignmentsController::class, 'showStudent'])->middleware(['auth', 'checkStudent'])->name('students.assignment.show');
Route::get('teachers/assignments/{assignment}',[AssignmentsController::class, 'showTeacher'])->middleware(['auth', 'checkTeacher'])->name('teachers.assignment.show');
Route::post('students/assignments/{assignment}/withdraw',[AssignmentsController::class, 'withdraw'])->middleware(['auth', 'checkStudent'])->name('students.assignment.withdraw');
Route::put('students/assignments/{assignment}',[AssignmentsController::class, 'updateStudent'])->middleware(['auth', 'checkStudent'])->name('students.assignment.update');
Route::put('teachers/assignments/{assignment}',[AssignmentsController::class, 'updateTeacher'])->middleware(['auth', 'checkTeacher'])->name('teachers.assignment.update');


Route::post('quiz/student', [QuizController::class, 'studentCode'])->middleware(['auth', 'checkStudent'])->name('quiz.student');
Route::put('quiz/student', [QuizController::class, 'updateTime'])->middleware(['auth', 'checkStudent'])->name('quiz.student.update.time');
Route::get('quiz/teacher', [QuizController::class, 'showQuizHome'])->middleware(['auth', 'checkTeacher'])->name('quiz.teacher.home');
Route::post('quiz/teacher', [QuizController::class, 'store'])->middleware(['auth' ,'checkTeacher'])->name('quiz.teacher.store');
Route::get('quiz/teacher/{quiz}/question', [QuizController::class, 'questionsShow'])->middleware(['auth', 'checkTeacher'])->name('quiz.teacher.questionshow');
Route::post('quiz/teacher/{quiz}/upQuestion', [QuizController::class, 'questionUp'])->middleware(['auth', 'checkTeacher'])->name('quiz.teacher.upQuestion');
Route::post('quiz/teacher/{quiz}/downQuestion', [QuizController::class, 'questionDown'])->middleware(['auth', 'checkTeacher'])->name('quiz.teacher.downQuestion');
Route::get('quiz/teacher/{user}/manageQuizes', [QuizController::class, 'showManageQuiz'])->middleware(['auth', 'checkTeacher'])->name('quiz.teacher.manageQuiz');
Route::get('quiz/teacher/{user}/manageQuizes/{id}/edit', [QuizController::class, 'edit'])->middleware(['auth', 'checkTeacher'])->name('quiz.teacher.edit.quiz');
Route::put('quiz/teacher/{user}/manageQuizes/{id}/update', [QuizController::class, 'update'])->middleware(['auth', 'checkTeacher'])->name('quiz.teacher.update.quiz');
Route::delete('quiz/teacher/{user}/manageQuizes/{id}/delete', [QuizController::class, 'delete'])->middleware(['auth', 'checkTeacher'])->name('quiz.teacher.delete');
Route::get('quiz/attendance/{id}', [QuizController::class, 'showAttendancePage'])->middleware(['auth', 'checkStudent'])->name('quiz.showAttendancePage');
Route::post('quiz/attendance/{id}', [QuizController::class, 'markAttendance'])->middleware(['auth', 'checkStudent'])->name('quiz.markAttendance');


Route::get('quiz/teacher/addquestion', [QuizequestionController::class, 'create'])->middleware(['auth', 'checkTeacher'])->name('quiz.teacher.question.create');
Route::post('quiz/teacher/addquestion', [QuizequestionController::class, 'store'])->middleware(['auth', 'checkTeacher'])->name('quiz.teacher.question.store');
Route::get('quiz/teacher/editquestion/{quizquestion}', [QuizequestionController::class, 'edit'])->middleware(['auth', 'checkTeacher'])->name('quiz.teacher.question.edit');
Route::put('quiz/teacher/editquestion/{quizquestion}', [QuizequestionController::class, 'update'])->middleware(['auth', 'checkTeacher'])->name('quiz.teacher.question.update');
Route::delete('quiz/teacher/deletequestion/{quizquestion}', [QuizequestionController::class, 'destroy'])->middleware(['auth', 'checkTeacher'])->name('quiz.teacher.question.delete');
Route::post('quiz/teacher/re_exam', [QuizController::class, 'reexam'])->middleware(['auth', 'checkTeacher'])->name('quiz.teacher.re-exam');

Route::get('quiz/student/start/{id}', [QuizController::class, 'startQuiz'])->middleware(['auth','checkStudent'])->name('quiz.start');
Route::put('quiz/student/late', [QuizController::class, 'late'])->middleware(['auth','checkStudent'])->name('quiz.late');
Route::post('quiz/student/endQuiz', [QuizController::class, 'endQuiz'])->middleware(['auth', 'checkStudent'])->name('quiz.end');
require __DIR__.'/auth.php';

app/Models/Assignment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class Assignment extends Model
{
    use HasFactory;
    protected $guarded = [''];

    public function assigned()
    {
        return $this->belongsToMany(User::class, 'user_assignment');
    }

    public function getRefPathAttribute()
    {
        return 'storage/'.$this->ref;
    }

    public function scopeSearchuser($query)
    {
        return $query->where('user_id',auth()->id());
    }

    public function deleteDoc()
    {
        Storage::delete($this->ref);
    }
}

app/Models/UserAssignment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class UserAssignment extends Model
{
    use HasFactory;
    protected $guarded = [''];
    protected $table = 'user_assignment';

    public function assignment()
    {
        return $this->belongsTo(Assignment::class);
    }

    public function assignedTo()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function getDocPathAttribute()
    {
        return 'storage/'.$this->doc;
    }

    public function deleteDoc()
    {
        Storage::delete($this->doc);
    }
}

resources/views/assignements/edit.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Erudite</title>

    <!-- font awesome cdn link  -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"

    />

    <link rel="preconnect" href="https://fonts.gstatic.com">

    <!-- custom css file link  -->
    <link rel="stylesheet" href="{{ asset('css/dashboard_blade.css') }}" />
    <style>
        .about{
            margin-top: 10rem;
        }

        section.about{
            min-height: 80vh;
        }
    </style>
  </head>
  <body>

    <!-- header section starts  -->

    <header>
      <div class="user">
        <img src="{{ asset('img/logo.png') }}" alt="" />
        <!--
          <h3 class="name">Erudite</h3>
        <p class="post">The Unified Platform</p>-->
      </div>

      <nav class="navbar">
        <ul>
          <li><a href="{{ route('assignment.home') }}">home</a></li>
          <li><a href="{{ route('assignments.show', $assignment->id) }}">Show</a></li>
          {{-- <li><a href="#about">Create Assignment</a></li>
          <li><a href="#education">Manage Assignment</a></li>
          <li><a href="#portfolio">Assignment list</a></li>
          <li><a href="#contact">Trivia Quiz</a></li> --}}
        </ul>
      </nav>
    </header>

    <!-- header section ends -->

    <div id="menu" class="fas fa-bars"></div>

    <!-- home section starts  -->

    <!-- home section ends -->

    <!-- about section starts  -->
    <section class="about" id="about">
    <div class="containe">
        <div class="text"><h2>Assignment Update</h2></div>
        <form action="{{ route('assignments.update', $assignment->id) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
           <div class="form-row">
            @if ($errors)
                <ul>
                    @foreach ($errors->all() as $message)
                        <li>{{ $message }}</li>
                    @endforeach
                </ul>
            @endif
           </div>

           <div class="form-row">
            <div class="input-data">
                 <input type="text" name='title' value="{{ old('title', $assignment->title) }}" required>
                 <div class="underline"></div>
                 <label for="">Assignment name</label>
              </div>

              <div class="input-data">
                <input type="date" name="due_date" value="{{ old('due_date', $assignment->due_date) }}"required>
                <div class="underline"></div>
                <label for=""></label>
             </div>
           </div>

           <div class="form-row">
            <div class="input-data">
                <input type="number" name="total_marks" value="{{ old('total_marks', $assignment->total_marks) }}" required>
                <div class="underline"></div>
                <label for="">Points</label>
             </div>

                <div class="input-data">
                 <input type="time" name="due_time" value="{{ old('due_time', substr($assignment->due_time,0,5)) }}">
                 <p>Current time in DB: {{ $assignment->due_time }}</p>
                 <div class="underline"></div>
                 <label for=""></label>
                </div>
           </div>

           <div class="form-row">
            <div class="input-data">
                <input type="text" name="description" value="{{ old('description', $assignment->description) }}" required>
                <div class="underline"></div>
                <label for="">Reference Text</label>
               </div>
            </div>

            <div class="form-row">
                <div>
                    <p>Current file in Database: <a href="{{ asset($assignment->ref_path) }}">View file</a></p>
                </div>
                <div class="input-data">
                    <input type="file" name="ref">
                    <div class="underline"></div>
                    <label for=""></label>
                   </div>
            </div>

            <div class="form-row submit-btn">
            <div class="input-data">
                <div class="inner"></div>
                <input type="submit" value="submit">
            </div>
            </div>
        </form>
     </div>
    </section>


    <!-- contact section ends -->

    <!-- scroll top button  -->

    {{-- <a href="#home" class="top">
      <img src="images/scroll-top-img.png" alt="" />
    </a> --}}

    <!-- jquery cdn link  -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <!-- custom js file link  -->
    <script src="{{ asset('js/dashboard_blade.js') }}"></script>
  </body>
</html>

resources/views/assignements/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">

    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="d-flex mb-3 justify-content-end">
                <a class="mr-3 btn btn-primary" href="{{ route('assignment.home') }}">
                    Back to Dashboard
                </a>

                {{-- <div class="">
                    <form action="{{ route('assignments.index') }}" method="GET">
                        <input type="text" name="search" class="" placeholder="Search Assignment" value="{{ request('search') }}">
                        <button type="submit" class="btn btn-success"><i class="fa fa-search"></i></button>
                    </form>
                </div> --}}
                {{-- <button type="button" class="ml-3 btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                    Search by ID
                </button> --}}
            </div>
            <div class="card">
                <div class="card-header">All Assignments</div>
                @foreach ($assignments as $assignment)
                    <div class="card-body">
                        <div class="media">
                            <div class="media-body">
                                <div class="d-flex justify-content-between">
                                    <h4><a href="{{ route('assignments.show', $assignment->id) }}">{{ $assignment->title }}</a></h4>
                                    <h6 class="float-right">Assignment ID: {{ $assignment->id }}</h6>
                                <div>

                                        <a href="{{ route('assignments.edit',$assignment->id) }}" class="btn btn-warning">Edit</a>
                                        <form action="{{ route('assignments.destroy',$assignment->id) }}" method="POST" class="inline">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete it?')">Delete</button>
                                        </form>


                                        {{-- @can('delete',$question)
                                            <form action="{{ route('questions.destroy',$assi->id) }}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete it?')">Delete</button>
                                            </form>
                                        @endcan --}}
                                    </div>
                                </div>
                                <div class="text-muted mb-2 text-right">
                                    <p>Due Date - {{ $assignment->due_date }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr>
                @endforeach

                <div class="card-footer">
                    {{-- {{ $questions->appends(['search' => request('search')])->links() }} --}}
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Give Question ID</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                <form action="{{ route('questions.showById') }}" method="POST">
                    @csrf
                    <input type="text" name="searchById" class="" placeholder="Question ID" value="{{ request('searchById') }}">
                    <button type="submit"class="btn btn-success"><i class="fa fa-search"></i></button>
                </form>
            </div>
          </div>
        </div>
      </div>
</div>
@endsection

resources/views/assignements/indexStudent.blade.php
@extends('layouts.app')
@section('content')
<div class="container">

    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="d-flex mb-3 justify-content-end">
                <a class="mr-3 btn btn-primary" href="{{ route('assignment.homestudent') }}">
                    Back to Dashboard
                </a>

                {{-- <div class="">
                    <form action="{{ route('assignments.index') }}" method="GET">
                        <input type="text" name="search" class="" placeholder="Search Assignment" value="{{ request('search') }}">
                        <button type="submit" class="btn btn-success"><i class="fa fa-search"></i></button>
                    </form>
                </div> --}}
                {{-- <button type="button" class="ml-3 btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                    Search by ID
                </button> --}}
            </div>
            <div class="card">

                <div class="card-header">All Assignments</div>
                @foreach ($assignments as $assignment)
                    <div class="card-body">
                        <div class="media">
                            <div class="media-body">
                                <div class="d-flex justify-content-between">
                                    <h4><a href="{{ route('students.assignment.show', $assignment->id) }}">{{ $assignment->assignment->title }}</a></h4>
                                    <h6 class="float-right">Assignment ID: {{ $assignment->assignment->id }}</h6>

                                    @if(!$assignment->submission_date)
                                        <div class="btn btn-danger">Not submitted</div>
                                    @else
                                        <a href="" class="btn btn-success">Submitted</a>
                                    @endif

                                    @if ($assignment->alloted_marks)
                                        <p>{{ $assignment->alloted_marks }} / {{ $assignment->assignment->total_marks }}</p>
                                    @else
                                        <p>Marks not alloted</p>
                                    @endif
                                <div>

                                        {{-- <a href="{{ route('assignments.edit',$assignment->id) }}" class="btn btn-warning">Edit</a>
                                        <form action="{{ route('assignments.destroy',$assignment->id) }}" method="POST" class="inline">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete it?')">Delete</button>
                                        </form> --}}
                                    </div>
                                </div>
                                <div class="text-muted mb-2 text-right">
                                    <p>Due Date - {{ $assignment->assignment->due_date }}</p>
                                    <p>Due time - {{ $assignment->assignment->due_time }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr>
                @endforeach

                <div class="card-footer">
                    {{-- {{ $questions->appends(['search' => request('search')])->links() }} --}}
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Give Question ID</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                <form action="{{ route('questions.showById') }}" method="POST">
                    @csrf
                    <input type="text" name="searchById" class="" placeholder="Question ID" value="{{ request('searchById') }}">
                    <button type="submit"class="btn btn-success"><i class="fa fa-search"></i></button>
                </form>
            </div>
          </div>
        </div>
      </div>
</div>
@endsection

resources/views/assignements/show.blade.php
@extends('layouts.app')
@section('page-level-styles')

@endsection
@section('content')
<div class="container">
    <a class="mb-3 btn btn-primary" href="{{ route('assignments.index') }}">
        Back
    </a>
    <div class="row justify-content-center">
        <div class="col-md-12">

            <div class="card">
                <div class="card-header">
                    <h1 class="pull-left">{{ $assignment->title }} &nbsp;&nbsp;&nbsp;ID:{{ $assignment->id }}</h1>
                    <a href="{{ route('assignments.edit',$assignment->id) }}" class="btn btn-warning pull-right">Edit</a>
                    <form action="{{ route('assignments.destroy',$assignment->id) }}" method="POST" class="mr-3 pull-right">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete it?')">Delete</button>
                    </form>
                </div>
                <div class="card-body">
                    {!! $assignment->description !!}

                    <p>Ref Doc: <a href="{{ asset($assignment->ref_path) }}">View file</a></p>
                </div>
                <div class="card-footer">
                    <div class="d-flex justify-content-between">
                        <div class="d-flex">

                        </div>
                        <div class="d-flex flex-column">
                            <div class="text-muted mb-2 text-right">
                                <p>Due Date - {{ $assignment->due_date }}</p>
                            </div>
                            <div class="text-muted mb-2 text-right">
                                <p>Due Time - {{ $assignment->due_time }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="card mt-4">
                <div class="card-header">
                    <h3 class="pull-left">Student List</h3>
                    <form action="{{ route('notifystudents', $assignment) }}" method="POST">
                        @csrf
                        <button type="submit" class="btn btn-danger pull-right ml-2">Notify Students</button>
                    </form>
                    <a href="" id="excel_button" class="btn btn-success pull-right">Download Excel</a>
                </div>
                <div class="card-body">

                    <table class="table table-hover" id="student_table">
                        <thead>
                            <tr>
                              <th scope="col">#</th>
                              <th scope="col">Name</th>
                              <th scope="col">Status</th>
                              <th scope="col">Submission Date</th>
                              <th scope="col">Submission Time</th>
                              <th scope="col">Marks</th>
                            </tr>
                          </thead>

                          @foreach ($userassignments as $userassignment)
                          <tr>
                            <th scope="row">{{ $loop->index+1 }}</th>

                                <td>{{ $userassignment->assignedTo->name }}</td>

                                @if(!$userassignment->submission_date)
                                    <td>Not Submitted</td>
                                @else
                                    <td><a href="{{ route('teachers.assignment.show', $userassignment->id) }}" class="">Submitted</a></td>
                                @endif

                                <td>{{ $userassignment->submission_date }}</td>
                                <td>{{ $userassignment->submission_time }}</td>

                                @if ($userassignment->alloted_marks)
                                    <td>{{ $userassignment->alloted_marks }} / {{ $userassignment->assignment->total_marks }}</td>
                                @else
                                    <td>Marks not alloted</td>
                                @endif

                          </tr>
                            @endforeach
                    </table>


                </div>
                <div class="card-footer">
                    <div class="d-flex justify-content-between">
                        <div class="d-flex">

                        </div>
                        <div class="d-flex flex-column">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
@endsection
@section('page-level-scripts')
<script type="text/javascript" src="https://unpkg.com/xlsx@0.15.1/dist/xlsx.full.min.js"></script>
<script>
    function html_table_to_excel(type)
    {
        var data = document.getElementById('student_table');

        var file = XLSX.utils.table_to_book(data, {sheet: "sheet1"});

        XLSX.write(file, { bookType: type, bookSST: true, type: 'base64' });

        XLSX.writeFile(file, 'file.' + type);
    }

    const export_button = document.getElementById('excel_button');

    export_button.addEventListener('click', () =>  {
        html_table_to_excel('xlsx');
    });
</script>
@endsection