routes/web.php
<?php

use App\Http\Controllers\AnswersController;
use App\Http\Controllers\AssignmentsController;
use App\Http\Controllers\FavoritesController;
use App\Http\Controllers\QuestionsController;
use App\Http\Controllers\QuizController;
use App\Http\Controllers\QuizequestionController;
use App\Http\Controllers\UsersController;
use App\Http\Controllers\VotesController;
use App\Models\User;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('home');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');


Route::get('userPhoto', [UsersController::class, 'userPhoto'])->middleware(['auth'])->name('userPhoto');
Route::post('userPhoto', [UsersController::class, 'userPhotoUplaod'])->middleware(['auth'])->name('userPhoto.upload');
Route::get('notifications', [UsersController::class, 'notifications'])->middleware(['auth'])->name('notifications');
Route::post('notifyStudents/{assignment}', [AssignmentsController::class, 'notifyStudents'])->middleware(['auth', 'checkTeacher'])->name('notifystudents');

Route::resource('questions', QuestionsController::class)->except('show');

Route::get('questions/{slug}',[QuestionsController::class, 'show'])->name('questions.show');
Route::post('questions/searchById',[QuestionsController::class, 'showById'])->name('questions.showById');

Route::post('questions/{question}/favorite',[FavoritesController::class, 'store'])->name('questions.favorite');
Route::delete('questions/{question}/unfavorite',[FavoritesController::class, 'destroy'])->name('questions.unfavorite');

Route::post('question/{question}/vote/{vote}', [VotesController::class, 'voteQuestion'])->name('questions.votes');
Route::post('answers/{answer}/vote/{vote}', [VotesController::class, 'voteAnswer'])->name('answers.votes');

Route::resource('questions.answers', AnswersController::class)->except(['index','show','create']);
Route::put('answers/{answer}/best-answer',[AnswersController::class, 'bestAnswer'])->name('answers.bestAnswer');

Route::get('/assignmentsindex',function(){
    return view('assignements.assignementshome');
})->middleware(['auth', 'checkTeacher'])->name('assignment.home');

Route::get('/assignmentsindexstudent',function(){
    $teachers = User::where('type','Teacher')->get();
    return view('assignements.assignementshomestudent',compact(['teachers']));
})->middleware(['auth', 'checkStudent'])->name('assignment.homestudent');

Route::resource('assignments', AssignmentsController::class)->middleware(['auth', 'checkTeacher']);

// Route::post('quiz/teacher', [QuizController::class, ''])->middleware(['auth']);
Route::post('students/assignments',[AssignmentsController::class, 'acceptAssignment'])->middleware(['auth', 'checkStudent'])->name('students.assignment.accept');
Route::get('students/assignments',[AssignmentsController::class, 'indexStudent'])->middleware(['auth', 'checkStudent'])->name('students.assignment.index');
Route::get('students/assignments/{assignment}',[AssignmentsController::class, 'showStudent'])->middleware(['auth', 'checkStudent'])->name('students.assignment.show');
Route::get('teachers/assignments/{assignment}',[AssignmentsController::class, 'showTeacher'])->middleware(['auth', 'checkTeacher'])->name('teachers.assignment.show');
Route::post('students/assignments/{assignment}/withdraw',[AssignmentsController::class, 'withdraw'])->middleware(['auth', 'checkStudent'])->name('students.assignment.withdraw');
Route::put('students/assignments/{assignment}',[AssignmentsController::class, 'updateStudent'])->middleware(['auth', 'checkStudent'])->name('students.assignment.update');
Route::put('teachers/assignments/{assignment}',[AssignmentsController::class, 'updateTeacher'])->middleware(['auth', 'checkTeacher'])->name('teachers.assignment.update');


Route::post('quiz/student', [QuizController::class, 'studentCode'])->middleware(['auth', 'checkStudent'])->name('quiz.student');
Route::put('quiz/student', [QuizController::class, 'updateTime'])->middleware(['auth', 'checkStudent'])->name('quiz.student.update.time');
Route::get('quiz/teacher', [QuizController::class, 'showQuizHome'])->middleware(['auth', 'checkTeacher'])->name('quiz.teacher.home');
Route::post('quiz/teacher', [QuizController::class, 'store'])->middleware(['auth' ,'checkTeacher'])->name('quiz.teacher.store');
Route::get('quiz/teacher/{quiz}/question', [QuizController::class, 'questionsShow'])->middleware(['auth', 'checkTeacher'])->name('quiz.teacher.questionshow');
Route::post('quiz/teacher/{quiz}/upQuestion', [QuizController::class, 'questionUp'])->middleware(['auth', 'checkTeacher'])->name('quiz.teacher.upQuestion');
Route::post('quiz/teacher/{quiz}/downQuestion', [QuizController::class, 'questionDown'])->middleware(['auth', 'checkTeacher'])->name('quiz.teacher.downQuestion');
Route::get('quiz/teacher/{user}/manageQuizes', [QuizController::class, 'showManageQuiz'])->middleware(['auth', 'checkTeacher'])->name('quiz.teacher.manageQuiz');
Route::get('quiz/teacher/{user}/manageQuizes/{id}/edit', [QuizController::class, 'edit'])->middleware(['auth', 'checkTeacher'])->name('quiz.teacher.edit.quiz');
Route::put('quiz/teacher/{user}/manageQuizes/{id}/update', [QuizController::class, 'update'])->middleware(['auth', 'checkTeacher'])->name('quiz.teacher.update.quiz');
Route::delete('quiz/teacher/{user}/manageQuizes/{id}/delete', [QuizController::class, 'delete'])->middleware(['auth', 'checkTeacher'])->name('quiz.teacher.delete');
Route::get('quiz/attendance/{id}', [QuizController::class, 'showAttendancePage'])->middleware(['auth', 'checkStudent'])->name('quiz.showAttendancePage');
Route::post('quiz/attendance/{id}', [QuizController::class, 'markAttendance'])->middleware(['auth', 'checkStudent'])->name('quiz.markAttendance');


Route::get('quiz/teacher/addquestion', [QuizequestionController::class, 'create'])->middleware(['auth', 'checkTeacher'])->name('quiz.teacher.question.create');
Route::post('quiz/teacher/addquestion', [QuizequestionController::class, 'store'])->middleware(['auth', 'checkTeacher'])->name('quiz.teacher.question.store');
Route::get('quiz/teacher/editquestion/{quizquestion}', [QuizequestionController::class, 'edit'])->middleware(['auth', 'checkTeacher'])->name('quiz.teacher.question.edit');
Route::put('quiz/teacher/editquestion/{quizquestion}', [QuizequestionController::class, 'update'])->middleware(['auth', 'checkTeacher'])->name('quiz.teacher.question.update');
Route::delete('quiz/teacher/deletequestion/{quizquestion}', [QuizequestionController::class, 'destroy'])->middleware(['auth', 'checkTeacher'])->name('quiz.teacher.question.delete');
Route::post('quiz/teacher/re_exam', [QuizController::class, 'reexam'])->middleware(['auth', 'checkTeacher'])->name('quiz.teacher.re-exam');

Route::get('quiz/student/start/{id}', [QuizController::class, 'startQuiz'])->middleware(['auth','checkStudent'])->name('quiz.start');
Route::put('quiz/student/late', [QuizController::class, 'late'])->middleware(['auth','checkStudent'])->name('quiz.late');
Route::post('quiz/student/endQuiz', [QuizController::class, 'endQuiz'])->middleware(['auth', 'checkStudent'])->name('quiz.end');
require __DIR__.'/auth.php';

app/Models/Question.php
<?php
namespace App\Models;

use App\Helpers\Votable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Question extends Model
{
    use HasFactory;
    use Votable;
    protected $guarded = ['id'];

    public function owner()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
    public function answers()
    {
        return $this->hasMany(Answer::class);
    }
    public function favorites()
    {
        return $this->belongsToMany(User::class)->withTimestamps();
    }
    public function votes()
    {
        return $this->morphToMany(User::class, 'vote')->withTimestamps();
    }
    public function askedTo()
    {
        return $this->belongsToMany(User::class, 'question_user');
    }

    //Accessor
    public function getFavoritesCountAttribute()
    {
        return $this->favorites()->count();
    }
    public function getIsFavoriteAttribute()
    {
        return $this->favorites()->where('user_id',auth()->id())->count() > 0;
    }
    public function getFavoriteStyleAttribute()
    {
        if($this->getIsFavoriteAttribute())
        {
            return "text-success";
        }
        return "text-black-50";
    }
    public function markBestAnswer(Answer $answer)
    {
        $this->best_answer_id = $answer->id;
        $this->save();
    }

    public function getUrlAttribute()
    {
        return "questions/{$this->slug}";
    }

    public function getCreatedDateAttribute()
    {
        return $this->created_at->diffForHumans();
    }

    public function getAnswerStyleAttribute()
    {
        if($this->answers->count() > 0)
        {
            if($this->best_answer_id)
            {
                return "has-best-answer";
            }
            return "answered";
        }
        return "not-answered";
    }

    //Mutators
    public function setTitleAttribute(string $title)
    {
        $this->attributes['title'] = $title;
        $this->attributes['slug'] = Str::slug($title);
    }


    //Query Scope
    public function scopeSearch($query)
    {
        $search = request('search');
        if($search)
        {
            return $query->where('title','like',"%$search%");
        }
        return $query;
    }

    public function scopeSearchId($query)
    {
        $searchId = request('searchById');
        if($searchId)
        {
            return $query->where('id',$searchId);
        }
        return $query;
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'organization',
        'type',
        'image1',
        'image2',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [

    ];


    public function isStudent()
    {
        return $this->type == "Student";
    }

    public function isTeacher()
    {
        return $this->type == "Teacher";
    }

    //Relationship Methods
    public function questions()
    {
        return $this->hasMany(Question::class);
    }

    public function answers()
    {
        return $this->hasMany(Answer::class);
    }

    public function quizzes()
    {
        return $this->hasMany(quiz::class, 'assigned_by');
    }

    public function quizAttempts()
    {
        return $this->hasMany(quizeattempt::class, 'student_id');
    }

    // public function favorites()
    // {
    //     return $this->belongsToMany(Question::class)->withTimestamps();
    // }
    public function toAnswer()
    {
        return $this->belongsToMany(Question::class, 'question_user');
    }

    public function assigned()
    {
        return $this->belongsToMany(Assignment::class, 'user_assignment');
    }

    public function votesQuestions()
    {
        return $this->morphedByMany(Question::class, 'vote')->withTimestamps();
    }
    public function votesAnswers()
    {
        return $this->morphedByMany(Answer::class, 'vote')->withTimestamps();
    }

    public function hasQuestionUpVote(Question $question)
    {
        return auth()->user()->votesQuestions()->where(['vote' => 1, 'vote_id' => $question->id, 'vote_type' => Question::class])->exists();
    }
    public function hasQuestionDownVote(Question $question)
    {
        return auth()->user()->votesQuestions()->where(['vote' => -1, 'vote_id' => $question->id, 'vote_type' => Question::class])->exists();
    }
    public function hasVoteForQuestion(Question $question)
    {
        return $this->hasQuestionUpVote($question) || $this->hasQuestionDownVote($question);
    }


    public function hasAnswerUpVote(Answer $answer)
    {
        return auth()->user()->votesAnswers()->where(['vote' => 1, 'vote_id' => $answer->id, 'vote_type' => Answer::class])->exists();
    }
    public function hasAnswerDownVote(Answer $answer)
    {
        return auth()->user()->votesAnswers()->where(['vote' => -1, 'vote_id' => $answer->id, 'vote_type' => Answer::class])->exists();
    }
    public function hasVoteForAnswer(Answer $answer)
    {
        return $this->hasAnswerUpVote($answer) || $this->hasAnswerDownVote($answer);
    }

    public function getAvatarAttribute()
    {
        $size = 40;
        $name = $this->name;
        return "https://ui-avatars.com/api/?name={$name}&rounded=true&size={$size}";
    }

    public function getUrl1Attribute()
    {
        return "users/{$this->id}/1.jpg";
    }

    public function getUrl2Attribute()
    {
        return "users/{$this->id}/2.jpg";
    }
}

app/Http/Controllers/QuestionsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateQuestionRequest;
use App\Http\Requests\UpdateQuestionRequest;
use App\Models\Question;
use App\Models\User;
use App\Notifications\NewQuestionAsked;
use Illuminate\Http\Request;


class QuestionsController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth'])->except('index','show');
    }

    public function index()
    {
        $questions = Question::search()->with('owner')->simplePaginate(6);
        return view('questions.index',compact(['questions']));
    }

    public function create()
    {
        // app('debugbar')->disable();
        $teachers = User::where('type','Teacher')->get();
        // dd($teachers);
        return view('questions.create', compact(['teachers']));
    }

    public function store(CreateQuestionRequest $request)
    {


        $question = auth()->user()->questions()->create([
            'title' => $request->title,
            'body' => $request->body
        ]);

        $question->askedTo()->attach($request->teachers);

        foreach($question->askedTo as $teacher)
        {
            $teacher->notify(new NewQuestionAsked($question));
        }


        session()->flash('success', 'Question Added!');
        return redirect(route('questions.index'));
    }

    public function show(Question $question)
    {
        $question->increment('views_count');
        return view('questions.show',compact(['question']));
    }

    public function showById()
    {
        $question = Question::searchId()->first();

        $question->increment('views_count');

        return view('questions.show',compact(['question']));
    }

    public function edit(Question $question)
    {
        if($this->authorize('update',$question)){
            return view('questions.edit', compact(['question']));
        }
        abort(403,'Access Denied.');
    }

    public function update(UpdateQuestionRequest $request, Question $question)
    {
        if($this->authorize('update',$question)){
            $question->update([
                'title' => $request->title,
                'body' => $request->body
            ]);

            session()->flash('success', 'Question Edited!');
            return redirect(route('questions.index'));
        }
        abort(403,'Access Denied.');
    }

    public function destroy(Question $question)
    {
        if($this->authorize('delete',$question)){
            $question->delete();

            session()->flash('success', 'Question Deleted!');
            return redirect(route('questions.index'));
        }
        abort(403);
    }
}

resources/views/questions/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header"><h2>Ask A Question!</h2></div>
                <div class="card-body">
                    <form action="{{ route('questions.update',$question->id) }}" method="POST">
                        @csrf
                        @method('PUT')
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input type="text"
                                       id="title"
                                       name="title"
                                       value="{{ old('title',$question->title) }}"
                                       class="form-control {{ $errors->has('title') ? 'is-invalid' : ''}}">
                                @error('title')
                                    <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="">Enter a Question</label>
                                <input type="hidden" id="body" name="body" value="{{ old('body',$question->body) }}">
                                <trix-editor input="body" class="form-control {{ $errors->has('body') ? 'is-invalid' : ''}}"></trix-editor>
                                @error('body')
                                    <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <button class="btn btn-success" type="submit">Submit</button>
                            </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('page-level-styles')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.css" integrity="sha512-CWdvnJD7uGtuypLLe5rLU3eUAkbzBR3Bm1SFPEaRfvXXI2v2H5Y0057EMTzNuGGRIznt8+128QIDQ8RqmHbAdg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
@endsection
@section('page-level-scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.js" integrity="sha512-/1nVu72YEESEbcmhE/EvjH/RxTg62EKvYWLG3NdeZibTCuEtW5M4z3aypcvsoZw03FAopi94y04GhuqRU9p+CQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
@endsection

resources/views/questions/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    {{-- {{ dd($questions) }} --}}
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="d-flex mb-3 justify-content-end">
                <a class="mr-3 btn btn-primary" href="{{ route('dashboard') }}">
                    Back to Dashboard
                </a>
                @if (auth()->user()->type == 'Student')
                    <a href="{{ route('questions.create') }}" class="btn btn-primary mr-3">Ask a question!</a>
                @endif
                <div class="">
                    <form action="{{ route('questions.index') }}" method="GET">
                        <input type="text" name="search" class="" placeholder="Search Title" value="{{ request('search') }}">
                        <button type="submit"class="btn btn-success"><i class="fa fa-search"></i></button>
                    </form>
                </div>
                <button type="button" class="ml-3 btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                    Search by ID
                </button>
            </div>
            <div class="card">
                <div class="card-header">All Questions</div>
                @foreach ($questions as $question)
                    <div class="card-body">
                        <div class="media">
                            <div class="stats mr-3">
                                <div class="votes text-center mb-3">
                                    <strong class="d-block">{{ $question->votes_count }}</strong> Votes
                                </div>
                                <div class="answers {{ $question->answer_style }} text-center mb-3">
                                    <strong class="d-block">{{ $question->answers_count }}</strong> Answers
                                </div>
                                <div class="views text-center">
                                    <strong class="d-block">{{ $question->views_count }}</strong> Views
                                </div>
                            </div>
                            <div class="media-body">
                                <div class="d-flex justify-content-between">
                                    <h4><a href="{{ $question->url }}">{{ $question->title }}</a></h4>
                                    <h6 class="float-right">Question ID: {{ $question->id }}</h6>
                                <div>
                                        @can('update',$question)
                                            <a href="{{ route('questions.edit',$question->id) }}" class="btn btn-warning">Edit</a>
                                        @endcan

                                        @can('delete',$question)
                                            <form action="{{ route('questions.destroy',$question->id) }}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete it?')">Delete</button>
                                            </form>
                                        @endcan
                                    </div>
                                </div>
                                <p>{!! \Illuminate\Support\Str::limit($question->body, 200) !!}</p>
                            </div>
                        </div>
                    </div>
                    <hr>
                @endforeach

                <div class="card-footer">
                    {{ $questions->appends(['search' => request('search')])->links() }}
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Give Question ID</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                <form action="{{ route('questions.showById') }}" method="POST">
                    @csrf
                    <input type="text" name="searchById" class="" placeholder="Question ID" value="{{ request('searchById') }}">
                    <button type="submit"class="btn btn-success"><i class="fa fa-search"></i></button>
                </form>
            </div>
          </div>
        </div>
      </div>
</div>
@endsection

resources/views/questions/show.blade.php
@extends('layouts.app')
@section('page-level-styles')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.css" integrity="sha512-CWdvnJD7uGtuypLLe5rLU3eUAkbzBR3Bm1SFPEaRfvXXI2v2H5Y0057EMTzNuGGRIznt8+128QIDQ8RqmHbAdg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<style>
    trix-toolbar .trix-button--icon-attach{
  display: none;
}
</style>
@endsection
@section('content')
<div class="container">
    <a class="mb-3 btn btn-primary" href="{{ route('questions.index') }}">
        Back
    </a>
    <div class="row justify-content-center">
        <div class="col-md-12">

            <div class="card">
                <div class="card-header"><h1>{{ $question->title }}</h1></div>
                <div class="card-body">
                    {!! $question->body !!}
                </div>
                <div class="card-footer">
                    <div class="d-flex justify-content-between">
                        <div class="d-flex">
                            <div>
                                @auth
                                    <form action="{{ route('questions.votes', [$question->id, 1]) }}" method="POST">
                                        @csrf
                                        <button title="Up-vote" type="submit" class="btn {{ auth()->user()->hasQuestionUpVote($question) ? 'text-success' : 'text-black-50' }}">
                                            <i class="fa fa-caret-up fa-3x"></i>
                                        </button>
                                    </form>
                                @else
                                    <a href="{{ route('login') }}" class="vote-up d-block text-center text-black-50" title="Up-Vote">
                                        <i class="fa fa-caret-up fa-3x"></i>
                                    </a>
                                @endauth
                                <a href="" class="vote-up d-block text-center text-black-50" title="Up-Vote">

                                </a>
                                <h4 class="m-0 text-muted text-center vote-count">{{ $question->votes_count }}</h4>
                                @auth
                                    <form action="{{ route('questions.votes', [$question->id, -1]) }}" method="POST">
                                        @csrf
                                        <button title="Down-vote" type="submit" class="btn {{ auth()->user()->hasQuestionDownVote($question) ? 'text-danger' : 'text-black-50' }}">
                                            <i class="fa fa-caret-down fa-3x"></i>
                                        </button>
                                    </form>
                                @else
                                    <a href="{{ route('login') }}" class="vote-up d-block text-center text-black-50" title="Down-Vote">
                                        <i class="fa fa-caret-down fa-3x"></i>
                                    </a>
                                @endauth
                            </div>
                            <div class="ml-5 mt-3">
                                @can('markAsFavorite',$question)
                                    <form action="{{ route($question->is_favorite ? 'questions.unfavorite' : 'questions.favorite',$question->id) }}" method="POST">
                                    @csrf
                                    @if ($question->is_favorite)
                                        @method('DELETE')
                                    @endif
                                    <button type="submit" class="btn {{ $question->favorite_style }}">
                                        <i class="fa fa-star fa-2x"></i>
                                    </button>
                                    </form>
                                @else
                                    <i class="fa fa-star-o text-success d-block fa-2x"></i>
                                @endcan

                                </a>
                                <h4 class="m-0 {{ $question->favorite_style }} text-center views-count">{{ $question->favorites_count }}</h4>
                            </div>
                        </div>
                        <div class="d-flex flex-column">
                            <div class="text-muted mb-2 text-right">
                                <p>Asked {{ $question->created_date }}</p>
                            </div>
                            <div class="d-flex mb-2">
                                <div>
                                    <img src="{{ $question->owner->avatar }}" alt="">

                                </div>
                                <div class="mt-2 ml-2">
                                    <p>{{ $question->owner->name }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @include('answers._index')
    @if (auth()->user()->type == "Teacher")
        @include('answers._create')
    @endif
</div>
@endsection
@section('page-level-scripts')
<script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.3.1/trix.js" integrity="sha512-/1nVu72YEESEbcmhE/EvjH/RxTg62EKvYWLG3NdeZibTCuEtW5M4z3aypcvsoZw03FAopi94y04GhuqRU9p+CQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
    function clearAll()
    {
        var output = document.getElementById("body1");
        output.value = "";
    }


    function runSpeechRecognition() {

		        var output = document.getElementById("body1");
		        // get action element reference
		        var action = document.getElementById("action");
                // new speech recognition object
                var SpeechRecognition = SpeechRecognition || webkitSpeechRecognition;
                var recognition = new SpeechRecognition();

                // This runs when the speech recognition service starts
                recognition.onstart = function() {
                    action.innerHTML = "<small>listening, please speak...</small>";
                };

                recognition.onspeechend = function() {
                    action.innerHTML = "<small>stopped listening, hope you are done...</small>";
                    recognition.stop();
                }

                // This runs when the speech recognition service returns result
                recognition.onresult = function(event) {
                    var transcript = event.results[0][0].transcript;
                    // console.log(transcript);
                    var original_val = output.value;
                    output.value = output.value + " " + transcript;
                    output.classList.remove("hide");
                };

                 // start recognition
                 recognition.start();
	        }
</script>
@endsection